services:
  - type: web
    name: adi-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webhook_adidas:app --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
